version: '3'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - sales-web
      - sales-web1
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 80:80

  javamelody:
    image: javamelody
    ports:
    - 1337:1337

  postgres:
    image: postgres:9.6.6
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=javamelodydb
  sales-core:
    image: cuba-sample-sales-core
    environment:
      - CUBA_DATASOURCE_HOST=postgres
      - CUBA_DATASOURCE_PORT=5432
      - CUBA_DATASOURCE_PASSWORD=1234
      - CUBA_DATASOURCE_USER=postgres
      - CUBA_DATASOURCE_DBNAME=javamelodydb
      - CUBA_CLUSTER_ENABLED=true
      - CUBA_TRUSTEDCLIENTPERMITTEDIPLIST=*.*.*.*
  sales-web:
    image: cuba-sample-sales-web
    environment:
      - CUBA_CONNECTIONURLLIST=http://sales-core:8079/app-core, http://sales-core1:8079/app-core
      - CUBA_USELOCALSERVICEINVOCATION=false

  sales-core1:
    image: cuba-sample-sales-core
    environment:
      - CUBA_DATASOURCE_HOST=postgres
      - CUBA_DATASOURCE_PORT=5432
      - CUBA_DATASOURCE_PASSWORD=1234
      - CUBA_DATASOURCE_USER=postgres
      - CUBA_DATASOURCE_DBNAME=javamelodydb
      - CUBA_CLUSTER_ENABLED=true
      - CUBA_TRUSTEDCLIENTPERMITTEDIPLIST=*.*.*.*
  sales-web1:
    image: cuba-sample-sales-web
    environment:
      - CUBA_CONNECTIONURLLIST=http://sales-core:8079/app-core, http://sales-core1:8079/app-core
      - CUBA_USELOCALSERVICEINVOCATION=false

