version: '3'

services:
  postgres:
    image: postgres:9.6.6
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=javamelodydb
  sales-core:
    image: cuba-sample-sales-core
    environment:
      - CUBA_DATASOURCE_HOST=postgres
      - CUBA_DATASOURCE_PORT=5432
      - CUBA_DATASOURCE_PASSWORD=1234
      - CUBA_DATASOURCE_USER=postgres
      - CUBA_DATASOURCE_DBNAME=javamelodydb
      - CUBA_CLUSTER_ENABLED=true
      - CUBA_TRUSTEDCLIENTPERMITTEDIPLIST=*.*.*.*
    ports:
    - "8079:8079"
  sales-web:
    image: cuba-sample-sales-web
    environment:
      - CUBA_CONNECTIONURLLIST=http://sales-core:8079/app-core, http://sales-core1:8079/app-core
      - CUBA_USELOCALSERVICEINVOCATION=false

    ports:
      - "8080:8080"

